
      AWSTemplateFormatVersion: '2010-09-09'
      Description: Apache Stack
      Resources:
         SimpleApache:
           Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
           Properties:
            ProductName: Amazon EC2 Linux Apache Webserver
            ProvisioningArtifactName: 'v1.0'
            ProvisioningParameters:
               - Key: "VPC"
                 Value: vpc-02228f11e26a1be72
               - Key: "RemoteAccessCIDR"
                 Value: 0.0.0.0/0
               - Key: "KeyPair"
                 Value: lon

         AnotherSimpleApache:
           Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
           Properties:
            ProductName: Amazon EC2 Linux Apache Webserver
            ProvisioningArtifactName: 'v1.0'
            ProvisioningParameters:
               - Key: "VPC"
                 Value: vpc-02228f11e26a1be72
               - Key: "RemoteAccessCIDR"
                 Value: 0.0.0.0/0
               - Key: "KeyPair"
                 Value: lon
      
                  
         
